### ISSUE TITLE
Make conceptual art

### ISSUE THREAD

**Issue by Anonymous4045** [letsbuilda/pyweek36#15]
This should be rough sketches of what blocks/levels might look like. Just enough to give asset designers something to work with.

**Comment by hkohko** [comment]
blocks, devices, level concept:
[concept_1](https://i.imgur.com/FeZII1n.png)

**Comment by Anonymous4045** [comment]
Hmm so are we throwing some of that out in favor of the slime? Or will the slime have a gun?

**Comment by hkohko** [comment]
> Hmm so are we throwing some of that out in favor of the slime? Or will the slime have a gun?

yes, we are throwing some of these in favor of the slime. I'll be making more concept that reflect out current story of the slime and the cave settings.

**Comment by hkohko** [comment]
![slime](https://github.com/letsbuilda/pyweek36/assets/91366057/1c53c027-7241-4bbc-8a90-34ed00d5ca80)
![slime2](https://github.com/letsbuilda/pyweek36/assets/91366057/730945b0-c09c-4510-9aa8-c05ac512d688)
![slime3](https://github.com/letsbuilda/pyweek36/assets/91366057/3e095852-44a7-4a94-acb0-0130e8e6f9f2)
![slime4](https://github.com/letsbuilda/pyweek36/assets/91366057/d8b0675b-ae82-48c5-a028-2085b42d35d3)

which base should i work upon? (mainly their expressions really)

**Comment by hkohko** [comment]
everything is set.
