### ISSUE TITLE
Define a setting

### ISSUE THREAD

**Issue by Anonymous4045** [letsbuilda/pyweek36#16]
Where and when in time the game takes place is pretty important for our assets and sound effects.

**Comment by Anonymous4045** [comment]
For time I'm thinking more in the future, which can explain the device. Maybe the player is a researcher in a giant lab and an experiment got out of control, causing dark matter to spread everywhere. Or maybe the player is an explorer and finds a cave with evil magic that they need to escape from. I think the cave could make more sense for level design, since stuff can look more randomly made when it's natural.

**Comment by Anonymous4045** [comment]
I think we're set on this one: the player is a slime who was doing its thing in a cave until it stumbled upon a magical object, like Pandora's box. When it touched it, evil was released and dark matter started spreading everywhere. The slime must escape the rapidly decaying cave to survive and live it's slimy life.

**Comment by hkohko** [comment]
agree with cave setting (already working on tiles with that theme)
