### ISSUE TITLE
Change player movement system

### ISSUE THREAD

**Issue by Anonymous4045** [letsbuilda/pyweek36#29]
To match the style of the player sprite (a slime), it would make more sense if the slime would jump rather than slide around. When space is pressed, the player should jump in the direction of the mouse. The force of the jump should scale with the distance the player is to the mouse.

**Comment by hkohko** [comment]
i'm not quite sure how the gameplay will feel though, since traditionally platformers are simple wasd movement. we can even only have left/right/spacebar like jump king. 

the involvement of the mouse feels kinda clunky to me. still open to the idea though

**Comment by Anonymous4045** [comment]
How about this: I implement it and make a few levels, then we decide which would have a better experience. I'll do that after the block logic though.
